import express from "express";
import sessionsRouter from "@SessionsRoutes";
import usersRouter from "@UsersRoutes/users.routes";
import productsRouter from "@ProductsRoutes/products.routes";
import uploadConfig from "@config/upload";
import isAuthenticated from "@middlewares/isAuthenticated";
import passwordRouter from "@UsersRoutes/password.routes";
import profileRouter from "@modules/users/routes/profile.routes";
const router = express.Router();
router.use("/products", productsRouter);
router.use("/users", usersRouter);
router.use("/sessions", sessionsRouter);
router.use("/uploads", isAuthenticated, express.static(uploadConfig.directory));
router.use("/password", passwordRouter);
router.use("/profile", profileRouter);
export default router;
